### ISSUE TITLE
Adding system variable

### ISSUE THREAD

**Issue by JonathanAlcantara** [globocom/GloboNetworkAPI#137]
[DEBUG] 05/Sep/2018:16:54:00 +0000 - U:USER.NAME, P:/path/, C:NoRequestContext, N:networkapi.extra_logging.middleware:89 , T:TOKEN, MSG:INICIO da requisição POST. Data: [{"name": "test_add_variables", "value": "testing", "description": "Vairable to test the insertion of variables in DB"}].
[INFO] 05/Sep/2018:16:54:00 +0000 - U:USER.NAME, P:/path/, C:NoRequestContext, N:networkapi.system.views:46 , T:TOKEN, MSG:VariableView
[ERROR] 05/Sep/2018:16:54:00 +0000 - U:USER.NAME, P:/path/, C:NoRequestContext, N:networkapi.system.views:83 , T:TOKEN, MSG:save_variable() takes exactly 3 arguments (4 given)
Traceback (most recent call last):
  File "P:/path2/networkapi/system/views.py", line 69, in post
    self.request.user, name, value, description)
TypeError: save_variable() takes exactly 3 arguments (4 given)
[WARNING] 05/Sep/2018:16:54:00 +0000 - U:USER.NAME,, P:/path/, C:NoRequestContext, N:networkapi.extra_logging.middleware:95 , T:TOKEN, MSG:Requisição concluída com falha. Conteúdo: [].
[DEBUG] 05/Sep/2018:16:54:00 +0000 - U:USER.NAME,, P:/path/, C:NoRequestContext, N:networkapi.extra_logging.middleware:99 , T:TOKEN, MSG:FIM da requisição.

**Comment by pantuza** [comment]
The commit fixes the issue!
