### ISSUE TITLE
Creating vip with more than 1 service port to the same pool (when pool does not exist yet)

### ISSUE THREAD

**Issue by alejandraklachquin** [globocom/GloboNetworkAPI#30]
If we try to create a vip with two service port (e.g., 80 and 8080) and we want both to use the same pool (e.g., servers at 8080, pool name "pooleg1") and that pool doesn't exist yet, the script tries to create the same pool (pooleg1) twice in the equipmts and we get an error. 
Workaround: first create the pool in the equipmts, then create the vip.

**Comment by laurapanzariello** [comment]
Bug fixed in NetworkAPIV3
