### ISSUE TITLE
VIP request return inconsistences

### ISSUE THREAD

**Issue by marcusgc** [globocom/GloboNetworkAPI#33]
POST request is returning id with type different from PUT request:

POST is returning number, PUT is returning string:

POST https://networkapi/api/vip/request/save/

Request: 
{"ip":101873,"finalidade":"Homologacao","cliente":"Usuario Interno","ambiente":"Homologacao BE-TESTE API","cache":"(nenhum)","timeout":"5","persistencia":"(nenhum)","host":"vip-daniel-com-pool.globoi.com","areanegocio":"time-evolucao","nome_servico":"vip-daniel-com-pool.globoi.com","vip_ports_to_pools":[{"port_vip":80,"server_pool":12494}]}

Response:
HTTP/1.1 201 CREATED
 {**"id": 11034**, "ip": 101873, "ipv6": null, "l7_filter": null, "filter_applied": null, "filter_rollback": null, "filter_valid": true, "applied_l7_datetime": null, "healthcheck_expect": null, "rule": null, "rule_applied": null, "rule_rollback": null, "areanegocio": "time-evolucao", "nome_servico": "vip-daniel-com-pool.globoi.com", "host": "vip-daniel-com-pool.globoi.com", "vip_ports_to_pools": [{"id": 12495, "requisicao_vip": 11034, "server_pool": 12494, "port_vip": 80}], "finalidade": "Homologacao", "cliente": "Usuario Interno", "ambiente": "Homologacao BE-TESTE API"}

PUT https://networkapi/api/vip/request/save/11034

Request:
{"ip":101873,"finalidade":"Homologacao","cliente":"Usuario Interno","ambiente":"Homologacao BE-TESTE API","cache":"(nenhum)","timeout":"5","persistencia":"source-ip","host":"teste-vip-daniel.lb.globoi.com","areanegocio":"time-evolucao","nome_servico":"teste-vip-daniel.lb.globoi.com","vip_ports_to_pools":[{"port_vip":80,"requisicao_vip":11034,"server_pool":12494}]}

Response:
{**"id": "11034"**, "ip": 101873, "ipv6": null, "l7_filter": null, "filter_applied": null, "filter_rollback": null, "filter_valid": true, "applied_l7_datetime": null, "healthcheck_expect": null, "rule": null, "rule_applied": null, "rule_rollback": null, "areanegocio": "time-evolucao", "nome_servico": "teste-vip-daniel.lb.globoi.com", "host": "teste-vip-daniel.lb.globoi.com", "vip_ports_to_pools": [{"id": null, "requisicao_vip": null, "server_pool": 12494, "port_vip": 80}], "finalidade": "Homologacao", "cliente": "Usuario Interno", "ambiente": "Homologacao BE-TESTE API"}

**Comment by laurapanzariello** [comment]
bug fixed in networkapiV3
