### ISSUE TITLE
Error when deleting pool request 

### ISSUE THREAD

**Issue by alejandraklachquin** [globocom/GloboNetworkAPI#38]
Fix delete method of pool:
api is trying to delete the members from the pool in the equipment, but as the pool does not exist in the equipment (it is a condition in order to delete the request!), we have an script error.
We have to remove this part:
                    command = settings.POOL_REAL_REMOVE % (id_pool, id_ip, port_ip)
                    code, _, _ = exec_script(command)
                    if code != 0:
                        raise exceptions.ScriptDeletePoolException()

in def delete(request) from api_pools/views.

**Comment by laurapanzariello** [comment]
Bug fixed in NetworkAPIV3
