### ISSUE TITLE
Validation missing in delete pool request (it must not be created)

### ISSUE THREAD

**Issue by alejandraklachquin** [globocom/GloboNetworkAPI#39]
Fix delete method of pool:
Add a validation step, where the pool must not be created in order to delete the request, ie, something like:
                    try:
                                        if server_pool.pool_created == True: 
                                                            raise exceptions.....
in def delete(request) from api_pools/views.

**Comment by laurapanzariello** [comment]
Bug fixed in NetworkAPIV3
