### ISSUE TITLE
Integrate django-rest-framework

### ISSUE THREAD

**Issue by snbuback** [globocom/GloboNetworkAPI#6]
- Integrate django-rest-framework, last stable version: 2.4.XXX
- All new apis will be in "/api" (urls.py)
- Install packages and put everything in requirements.txt (this file must keep in sync)
- Use HTTP Basic Authentication (_if necessary_ implement new authentication provider in django rest framework: http://www.django-rest-framework.org/api-guide/authentication#custom-authentication)

**Comment by marcusgc** [comment]
integrated. features being migrated.
